### ISSUE TITLE
Add track length to the search results and the user queue

### ISSUE THREAD

**Issue by cyancey76** [mxew/firetable-user#23]
Add track length to the search results and the user queue. I use the track lengths to check to see if its the right version of a song that I want.

**Comment by ghost** [comment]
we're only getting `cid`, `name`, and `type` in the front-end right now. need to to add track length ( and maybe art thumbnail if possible ) to the database return.

**Comment by mxew** [comment]
This was intentionally omitted. Youtube's API does not include track length in the response of their search call. Rather than add in an additional external call, and use up additional Youtube API Quota Units (especially an issue when bringing in big Youtube lists all at once), song length was left out. The hostbot gets this data instead when it is time to play a track (it is returned in the results of the api call the hostbot is already using to check for de-listed, deleted, or copyright-restricted videos.
