### ISSUE TITLE
Chat window occasionally turns black

### ISSUE THREAD

**Issue by cyancey76** [mxew/firetable-user#77]
Sometimes the chat will turn black and you have to click over to the people or queue tab and back to get it to appear again.

I can't figure out how to duplicate the issue yet but its happening several times a day.

**Comment by ghost** [comment]
I am tracking this one down. It has to do with the system relogging the user in randomly which adds an extra class that confuses the grid and what content goes where. i can fix this via how the classes are managed but not sure about how to fix the log in issue (and what else is it causing?)

**Comment by mxew** [comment]
I’ve seen this too in mobile occasionally

**Comment by mxew** [comment]
As for the login issue, that is being caused by firebase auth’s onauthstatechange event firing seemingly randomly. I checked, and when it happens it will fire a full logout and back in cycle. So a user will be logged in -> logged out -> logged in. We could possibly stop listening to that event after we detect a user is logged in, and then just manually detect log outs via the logout button being clicked. Unclear how the firebase server would react to our requests during the brief moments that our client is “unauthenticated”.
